### ISSUE TITLE
bffnt.py unknown version errors

### ISSUE THREAD

**Issue by acleiker2** [ObsidianX/3dstools#10]
Hello, when trying to use bffnt.py to extract some bffnt files from the Wii U version of Zelda Breath of the Wild, I get the following errors in Linux.
Unknown version: 0x00000003 (expected 0x04000000)
When trying under windows I am getting the following error
Invalid FFNT magic bytes: b'FFNT' (expected FFNT)
Would it be possible to update bffnt.py to handle these newer BFFNT files?

**Comment by Random0666** [comment]
I have the same problem

**Comment by SamusAranX** [comment]
For some reason, this won't work with Python 3, that's where your "Invalid FFNT magic bytes" error comes from.
The version error seems to be legit, though.

**Comment by ObsidianX** [comment]
I don't have time at the moment to add support for a new BFFNT version but I'm more than happy to accept pull requests :)

**Comment by fsd523** [comment]
I also received in the windows system:'Unknown version: 0x00000003 (expected 0x04000000)'errors.
Which version of python should I use?

**Comment by ObsidianX** [comment]
> I also received in the windows system:'Unknown version: 0x00000003 (expected 0x04000000)'errors.
Which version of python should I use?

That error means you're trying to parse a newer version of BFFNT than this script understands.

**Comment by CyberSlimp** [comment]
Can You fix "Unknown version: 0x00000003 (expected 0x04000000)" please?

**Comment by ObsidianX** [comment]
It's not a bug, that's adding support for version 4 which may be significantly different.

**Comment by CyberSlimp** [comment]
Yes exactly. Already read the specification. Support for the 4th version is planned?

**Comment by ObsidianX** [comment]
I will not be adding support, myself, but I am always open to Pull Requests.

**Comment by Tyulis** [comment]
Can you try now? I pull requested to add version 3.

**Comment by CyberSlimp** [comment]
Hi, great news. 
I try unpack bffnt but see error
`G:\Zelda-Decompress\3dstools-master>bffnt.py -xf CKingMain.bffnt
Traceback (most recent call last):
  File "G:\Zelda-Decompress\3dstools-master\bffnt.py", line 1257, in <module>
    bffnt.read(args.file)
  File "G:\Zelda-Decompress\3dstools-master\bffnt.py", line 160, in read
    self._parse_tglp_header(data[position:position + TGLP_HEADER_SIZE])
  File "G:\Zelda-Decompress\3dstools-master\bffnt.py", line 654, in _parse_tglp_header
    magic, section_size, cell_width, cell_height, baseline_position, max_char_width, sheet_size, num_sheets, sheet_pixel_format, num_sheet_cols, num_sheet_rows, sheet_width, sheet_height, sheet_data_offset = struct.unpack(TGLP_HEADER_STRUCT_3 % self.order, data)
struct.error: unpack requires a string argument of length 32`

I make something wrong?

**Comment by Tyulis** [comment]
I think i see what kind of error it is, but can you send the bffnt file, for further testing?

**Comment by CyberSlimp** [comment]
OK, i add file. I use 2.7 Python bcs with v3 I had some problems
[CKingMain.zip](https://mega.nz/#!cKphDYJQ!Jfs5mNShYof4-sGLDeGaKFVPo0LVw_5T-knBDKt6lOM)

**Comment by Tyulis** [comment]
Ok... Not as i thought, this is not a "renamed" CFNT (which have normally version 3). I tried and it works if extracted as v4, but... The result is very strange. A bugged blue image. I see 2 possibilities: a bug in the decompression algorithm (because the texture is compressed), or a different structure. While i haven't find the problem, this issue has to be reopened...

**Comment by Tyulis** [comment]
Do you have some other files like this one, to do comparisons? This would be useful.

**Comment by CyberSlimp** [comment]
Hello.
I dont have more same files, but i can convert it file to good reading GTX files and convert it to DDS with this [BFFNTtoGTX.zip](https://github.com/ObsidianX/3dstools/files/1308008/BFFNTtoGTX.zip) quickbms script, And after some steps i can make PNG - ![ckingmsg_43x51_0](https://user-images.githubusercontent.com/3046130/30507954-c7e1e92c-9a94-11e7-8e23-743436c06d6f.png)

But i cant convert it back to BFFNT file after make changes in PNG(

**Comment by Tyulis** [comment]
I don't really know GTX and DDS formats, but i see that this script extracts header and creates GTX headers from this, but left data unchanged... What do you used to convert GTX to DDS and DDS to PNG?

**Comment by CyberSlimp** [comment]
Hi.
For GTX to DDS i use [this script](https://mega.nz/#!dPQ3VQYQ!YySOzX8GGSEtlrHwWpsleMjNYkm4FedkiaPVrUVBsWk)
For DDS to PNG [this software](http://www.ddsconverter.com/)
And sometime i use fix for DDS (if corrupt background),[ its a QuickBMS script.](https://mega.nz/#!pDRFERgD!aTwj9NtfaD1lVhhYV03JLf5seAwtqQ4zayNV8i4Grsk)

**Comment by Tyulis** [comment]
Ok, i'll try to see that. Thanks for help.

**Comment by Tyulis** [comment]
Fixed the version issue. The problem is with texture decompression or format
