### ISSUE TITLE
when extract nes remix .arc files ,show errors.

### ISSUE THREAD

**Issue by kavid** [ObsidianX/3dstools#13]
E:\website\WiiU\tools\3dstools-master\3dstools-master>sarc.py -xf Parts.arc
Invalid filename:
Hash: 0x0 (expected 0x75a5b6)
SARC archive is invalid

Can you add "wiiu nes remix Pack "to extract and pack .arc files to support?
thank you
attachment is "nes remix pack" orgin files.
[layout.zip](https://github.com/ObsidianX/3dstools/files/1133582/layout.zip)

**Comment by Tyulis** [comment]
Were these files already GZip-compressed in the game?

**Comment by Tyulis** [comment]
It is because these files don't store files names. I will try to pull request

**Comment by kavid** [comment]
I can't find the .saht files .

it like mario kart 7‘s sarc
no files list in the sarc files。’

**Comment by Tyulis** [comment]
Ok... It is easy to extract them with indices as files names, but not to repack

**Comment by Tyulis** [comment]
Can you try with that (extracting and repacking)? Files names are ugly, but it is the only way I found
[https://gist.github.com/68bf97cc5bbde7600192257373f54ff5](https://gist.github.com/68bf97cc5bbde7600192257373f54ff5)

**Comment by kavid** [comment]
E:\website\WiiU\tools\QuickBMS\dir>sarc.py -xf Parts.arc
Traceback (most recent call last):
  File "E:\website\WiiU\tools\QuickBMS\dir\sarc.py", line 543, in <module>
    sarc.read()
  File "E:\website\WiiU\tools\QuickBMS\dir\sarc.py", line 238, in read
    self._parse_header(partial_data[:SARC_HEADER_LEN])
  File "E:\website\WiiU\tools\QuickBMS\dir\sarc.py", line 345, in _parse_header
    int_bom = int.from_bytes(bom, 'big') #for error messages
AttributeError: type object 'int' has no attribute 'from_bytes'


my python is 2.7.16

**Comment by Tyulis** [comment]
Oops, stupid error, I forgot to tet with python2, sorry. Now it should work
[https://gist.github.com/ac35e2ccd18d1528da151ae79491b65b](https://gist.github.com/ac35e2ccd18d1528da151ae79491b65b)

**Comment by kavid** [comment]
it's extraction is work.
but repack don't work

i use "sarc.py -xf PartsHeri1.arc" to extract .bin files
then i put these .bin fiels to partsheri1 subdir
use sarc.py -cf Parts111.arc PartsHeri1 to repack
i get files size is 14,291kb,but origin files size is 14,969kb

what ‘ wrong with me？

**Comment by Tyulis** [comment]
This program repacks by default in little endian, so to make it working on Wii U, you must add the -b option. For the file size, i think it is a padding issue, and I hope that it has no influence

**Comment by Tyulis** [comment]
Does it work?

**Comment by kavid** [comment]
it work! thank u.

**Comment by Tyulis** [comment]
Cool! I pull request. You can close the issue

**Comment by ObsidianX** [comment]
Fixed #14
